name: build and deploy to gh pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.79.1'
          extended: true

      - name: Build
        run: hugo --gc --minify
        env:
          HUGO_ENV: production
          HUGO_BASEURL: 'https://wikipaka.wtf/'

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          keep_history: true
          build_dir: public
          jekyll: false
          fqdn: wikipaka.wtf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
